import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';
export const categories:Record<string,string>={jpg:'Images',jpeg:'Images',png:'Images',webp:'Images',gif:'Images',svg:'Images',bmp:'Images',tiff:'Images',mp4:'Videos',mov:'Videos',avi:'Videos',mkv:'Videos',webm:'Videos',mp3:'Audio',wav:'Audio',m4a:'Audio',aac:'Audio',flac:'Audio',pdf:'Documents',doc:'Documents',docx:'Documents',txt:'Documents',rtf:'Documents',xls:'Spreadsheets',xlsx:'Spreadsheets',csv:'Spreadsheets',ppt:'Presentations',pptx:'Presentations',zip:'Archives',rar:'Archives','7z':'Archives',tar:'Archives',gz:'Archives',exe:'Executables',msi:'Executables',js:'Code',ts:'Code',jsx:'Code',tsx:'Code',html:'Code',css:'Code',py:'Code',java:'Code',cpp:'Code',json:'Code',ttf:'Fonts',otf:'Fonts',woff:'Fonts',woff2:'Fonts',psd:'Design Files',ai:'Design Files',sketch:'Design Files',blend:'3D Files',obj:'3D Files',fbx:'3D Files'};
export type OrganizationRule={id?:number;name:string;fileTypes:string[];extensions:string[];keywords:string[];destination:string;enabled:boolean;priority:number};
export type ScannedFile={path:string;name:string;ext:string;category:string;size:number;created:string;modified:string};
export type PreviewFile=ScannedFile&{root:string;destination:string;matchedRule:string;reason:string};
export function validateRuleDestination(value:string){const raw=value.trim().replace(/\\/g,'/');if(!raw||raw.startsWith('/')||/^[a-z]:/i.test(raw))throw Error('Destination must be a folder path inside the selected folder.');const parts=raw.split('/');if(parts.some(p=>!p||p==='.'||p==='..'||p.includes(':')))throw Error('Destination cannot contain empty, dot, or parent folder segments.');return parts.join('/');}
export function matchRule(file:Pick<ScannedFile,'name'|'ext'|'category'>,rules:OrganizationRule[]){const name=file.name.toLowerCase(),ext=file.ext.replace(/^\./,'').toLowerCase();const keywordMatches=(r:OrganizationRule)=>r.keywords.some(k=>k.trim()&&name.includes(k.trim().toLowerCase()));const candidates=rules.filter(r=>r.enabled&&(keywordMatches(r)||(r.extensions||[]).some(e=>e.replace(/^\*?\.?/,'').toLowerCase()===ext)||(r.fileTypes||[]).includes(file.category)));candidates.sort((a,b)=>Number(keywordMatches(b))-Number(keywordMatches(a))||a.priority-b.priority||(a.id||0)-(b.id||0));const rule=candidates[0];if(!rule)return null;const keyword=rule.keywords.find(k=>k.trim()&&name.includes(k.trim().toLowerCase()));return {rule,reason:keyword?`Filename contains “${keyword}”`:(rule.extensions||[]).some(e=>e.replace(/^\*?\.?/,'').toLowerCase()===ext)?`Extension .${ext}`:`File type ${file.category}`};}
export function previewOrganization(files:ScannedFile[],root:string,mode:string,rules:OrganizationRule[],exists:(p:string)=>boolean){const reserved=new Set<string>();return files.map(file=>{const match=matchRule(file,rules);const date=new Date(file.modified);const fallback=mode==='date'?[String(date.getFullYear()),date.toLocaleString('en-US',{month:'long'})]:mode==='type-date'?[file.category,String(date.getFullYear()),date.toLocaleString('en-US',{month:'long'})]:[file.category];const custom=match?path.resolve(root,match.rule.destination,file.name):'';const safeCustom=custom&&isInside(root,custom);const intended=safeCustom?custom:path.join(root,...fallback,file.name);if(path.resolve(file.path)===path.resolve(intended))return null;const final=conflictSafePath(intended,exists,reserved);reserved.add(final.toLowerCase());return {...file,root,destination:final,matchedRule:safeCustom?match!.rule.name:'Default organization',reason:safeCustom?match!.reason:`Default ${mode==='date'?'date':mode==='type-date'?'file type + date':'file type'} organization`};}).filter((x):x is PreviewFile=>x!==null);}
export function categorize(filename:string){return categories[path.extname(filename).slice(1).toLowerCase()]||'Other';}
export function isInside(root:string,target:string){const relative=path.relative(path.resolve(root),path.resolve(target));return relative!==''&&!relative.startsWith(`..${path.sep}`)&&relative!=='..'&&!path.isAbsolute(relative);}
export function conflictSafePath(dest:string,exists:(path:string)=>boolean,reserved=new Set<string>()){if(!exists(dest)&&!reserved.has(dest.toLowerCase()))return dest;const ext=path.extname(dest),base=dest.slice(0,-ext.length);let n=1;while(exists(`${base} (${n})${ext}`)||reserved.has(`${base} (${n})${ext}`.toLowerCase()))n++;return `${base} (${n})${ext}`;}
function ensureSafeDirectory(root:string,directory:string,create:boolean){if(path.resolve(directory)!==path.resolve(root)&&!isInside(root,directory))throw Error('Directory must stay inside the selected folder.');const relative=path.relative(root,directory);let current=path.resolve(root);for(const segment of relative.split(path.sep).filter(Boolean)){current=path.join(current,segment);let info;try{info=fs.lstatSync(current)}catch(error:any){if(error.code!=='ENOENT'||!create)throw error;fs.mkdirSync(current);info=fs.lstatSync(current)}if(info.isSymbolicLink()||!info.isDirectory())throw Error('Symbolic links and non-folder destinations are not allowed.');}}
export function moveFileSafe(source:string,destination:string,root:string){const src=path.resolve(source),rootAbs=path.resolve(root),wanted=path.resolve(destination);if(!isInside(rootAbs,src)||!isInside(rootAbs,wanted))throw Error('File operation must stay inside the selected folder.');ensureSafeDirectory(rootAbs,path.dirname(src),false);const st=fs.lstatSync(src);if(!st.isFile()||st.isSymbolicLink())throw Error('Only regular files can be moved.');ensureSafeDirectory(rootAbs,path.dirname(wanted),true);const final=conflictSafePath(wanted,fs.existsSync);fs.renameSync(src,final);return final;}
export function undoFileMove(original:string,moved:string,root:string){const src=path.resolve(moved),dest=path.resolve(original),rootAbs=path.resolve(root);if(!isInside(rootAbs,src)||!isInside(rootAbs,dest))throw Error('Undo must stay inside the original selected folder.');if(!fs.existsSync(src))return false;ensureSafeDirectory(rootAbs,path.dirname(src),false);ensureSafeDirectory(rootAbs,path.dirname(dest),true);fs.renameSync(src,conflictSafePath(dest,fs.existsSync));return true;}
export async function hashFile(file:string){const hash=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(file))hash.update(chunk);return hash.digest('hex');}
