import { app, BrowserWindow, dialog, ipcMain, Notification } from 'electron';
import path from 'node:path'; import fs from 'node:fs';
import initSqlJs, { Database } from 'sql.js';
import { categories, categorize, isInside, conflictSafePath, moveFileSafe, undoFileMove, hashFile, previewOrganization, validateRuleDestination, matchRule, type OrganizationRule } from './core';
import { requestAiSuggestions, filesWithoutCustomRules } from './ai';
import type { AiSuggestion } from './ai-decisions';
let db:Database; let dbPath:string;
function persist(){fs.writeFileSync(dbPath,Buffer.from(db.export()));}
function all(sql:string,params:any[]=[]){const q=db.prepare(sql);q.bind(params);const out:any[]=[];while(q.step())out.push(q.getAsObject());q.free();return out;}
function run(sql:string,params:any[]=[]){db.run(sql,params);persist();return db.exec('SELECT last_insert_rowid() AS id')[0]?.values[0]?.[0];}
function safeRoot(p:string){const r=path.resolve(p);if(!fs.existsSync(r)||!fs.statSync(r).isDirectory())throw Error('Choose a folder that exists and can be opened.');return fs.realpathSync(r);}
function scan(root:string){root=safeRoot(root);const out:any[]=[];function walk(dir:string){let entries;try{entries=fs.readdirSync(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(e.name.startsWith('.')||e.name==='System Volume Information'||e.name==='$RECYCLE.BIN'||e.name==='node_modules')continue;const p=path.join(dir,e.name);if(e.isSymbolicLink())continue;if(e.isDirectory()){walk(p);continue;}try{const s=fs.statSync(p);if(s.isFile())out.push({path:p,name:e.name,ext:path.extname(e.name).slice(1).toLowerCase(),category:categorize(e.name),size:s.size,created:s.birthtime.toISOString(),modified:s.mtime.toISOString()});}catch{}}}walk(root);return out;}
async function initDb(){const SQL=await initSqlJs({locateFile:(file)=>path.join(path.dirname(require.resolve('sql.js')),file)});dbPath=path.join(app.getPath('userData'),'fileflow.sqlite');db=fs.existsSync(dbPath)?new SQL.Database(fs.readFileSync(dbPath)):new SQL.Database();db.run(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT); CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY, name TEXT, folder TEXT); CREATE TABLE IF NOT EXISTS operations(id INTEGER PRIMARY KEY, folder TEXT, moved INTEGER, status TEXT, created TEXT); CREATE TABLE IF NOT EXISTS moved_files(id INTEGER PRIMARY KEY, operation_id INTEGER, source TEXT, destination TEXT); CREATE TABLE IF NOT EXISTS rules(id INTEGER PRIMARY KEY, name TEXT NOT NULL, condition TEXT, operator TEXT, value TEXT, action TEXT, target TEXT, file_types TEXT NOT NULL DEFAULT '[]', extensions TEXT NOT NULL DEFAULT '[]', keywords TEXT NOT NULL DEFAULT '[]', destination TEXT NOT NULL DEFAULT '', enabled INTEGER NOT NULL DEFAULT 1, priority INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);`);const cols=all('PRAGMA table_info(rules)').map((r:any)=>r.name);for(const [name,type] of [['file_types',"TEXT NOT NULL DEFAULT '[]'"],['extensions',"TEXT NOT NULL DEFAULT '[]'"],['keywords',"TEXT NOT NULL DEFAULT '[]'"],['destination',"TEXT NOT NULL DEFAULT ''"],['enabled','INTEGER NOT NULL DEFAULT 1'],['priority','INTEGER NOT NULL DEFAULT 0']] as const)if(!cols.includes(name))db.run(`ALTER TABLE rules ADD COLUMN ${name} ${type}`);db.run(`UPDATE rules SET extensions=json_array(lower(trim(value,' .'))) WHERE extensions='[]' AND condition='extension' AND value IS NOT NULL AND value<>''; UPDATE rules SET destination=target WHERE destination='' AND target IS NOT NULL;`);persist();}
function createWindow(){const w=new BrowserWindow({width:1440,height:900,minWidth:1060,minHeight:700,backgroundColor:'#0c0e12',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});if(process.env.VITE_DEV_SERVER_URL)w.loadURL(process.env.VITE_DEV_SERVER_URL);else w.loadFile(path.join(__dirname,'../dist/index.html'));}
app.whenReady().then(async()=>{await initDb();createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
ipcMain.handle('app:version',()=>app.getVersion());
ipcMain.handle('updates:check',()=>({status:'unconfigured'}));
ipcMain.handle('folder:select',async()=>{const r=await dialog.showOpenDialog({properties:['openDirectory']});return r.canceled?null:r.filePaths[0]});
ipcMain.handle('rules:select-destination',async(_e,root:string)=>{const base=safeRoot(root),r=await dialog.showOpenDialog({defaultPath:base,properties:['openDirectory']});if(r.canceled||!r.filePaths[0])return null;const picked=fs.realpathSync(r.filePaths[0]);if(!isInside(base,picked))throw Error('Rule destinations must remain inside the selected organization folder.');return path.relative(base,picked).split(path.sep).join('/')||null;});
ipcMain.handle('files:scan',(_e,p)=>scan(p));
ipcMain.handle('files:preview',(_e,p,mode)=>{const root=safeRoot(p);return previewOrganization(scan(root),root,mode,loadRules(),fs.existsSync)});
ipcMain.handle('ai:status',()=>({configured:Boolean(process.env.OPENAI_API_KEY?.trim())}));
ipcMain.handle('ai:suggest',async(_e,p:string)=>{const settings=Object.fromEntries(all('SELECT * FROM settings').map((x:any)=>[x.key,JSON.parse(x.value)])) as any;if(!settings.aiEnabled)return {status:'disabled',suggestions:[]};const root=safeRoot(p),files=scan(root),eligible=filesWithoutCustomRules(files,loadRules(),matchRule);const rawThreshold=Number(settings.aiConfidenceThreshold),threshold=[.9,.8,.7,.6].includes(rawThreshold)?rawThreshold:.8;return requestAiSuggestions(eligible,root,process.env.OPENAI_API_KEY,threshold);});
ipcMain.handle('ai:accepted-preview',(_e,p:string,accepted:AiSuggestion[])=>{const root=safeRoot(p),rules=loadRules(),current=scan(root),reserved=new Set<string>();return accepted.flatMap(item=>{try{const source=path.resolve(item.path);if(!isInside(root,source))return [];const file=current.find(f=>path.resolve(f.path)===source);if(!file||matchRule(file,rules))return [];const relative=validateRuleDestination(item.destination),destination=path.resolve(root,relative,file.name);if(!isInside(root,destination))return [];const final=conflictSafePath(destination,fs.existsSync,reserved);reserved.add(final.toLowerCase());return [{...file,root,destination:final,matchedRule:'AI Smart Organize',reason:item.reason}];}catch{return [];}});});
ipcMain.handle('files:organize',(_e,items:any[],dryRun:boolean)=>{if(dryRun)return {moved:0,dryRun:true};const records:any[]=[];for(const f of items){try{const root=safeRoot(f.root),src=path.resolve(f.path),dest=path.resolve(f.destination);if(src===dest)continue;records.push([src,moveFileSafe(src,dest,root)]);}catch{continue;}}db.run('BEGIN');db.run('INSERT INTO operations(folder,moved,status,created) VALUES(?,?,?,?)',[items[0]?.root||'',records.length,'Completed',new Date().toISOString()]);const id=Number(db.exec('SELECT last_insert_rowid()')[0].values[0][0]);for(const [s,d] of records)db.run('INSERT INTO moved_files(operation_id,source,destination) VALUES(?,?,?)',[id,s,d]);db.run('COMMIT');persist();if(records.length&&Notification.isSupported())new Notification({title:'FileFlow organized files',body:`FileFlow organized ${records.length} files.`}).show();return {moved:records.length,id};});
ipcMain.handle('operation:history',()=>all('SELECT * FROM operations ORDER BY id DESC'));
ipcMain.handle('operation:undo',(_e,id:number)=>{const operation=all('SELECT folder FROM operations WHERE id=?',[id])[0] as any,rows=all('SELECT * FROM moved_files WHERE operation_id=? ORDER BY id DESC',[id]);let restored=0;for(const r of rows){try{if(operation?.folder&&undoFileMove(r.source,r.destination,safeRoot(operation.folder)))restored++;}catch{}}run('UPDATE operations SET status=? WHERE id=?',['Undone',id]);return {restored};});
ipcMain.handle('files:duplicates',async(_e,p)=>{const files=scan(p), groups=new Map<string,any[]>();for(const f of files){try{const k=await hashFile(f.path);groups.set(k,[...(groups.get(k)||[]),f]);}catch{}}return [...groups.values()].filter(g=>g.length>1).flat();});
ipcMain.handle('files:stats',(_e,p)=>{const f=scan(p);const byCategory:Record<string,number>={};for(const x of f)byCategory[x.category]=(byCategory[x.category]||0)+x.size;return {total:f.length,size:f.reduce((a,x)=>a+x.size,0),largest:[...f].sort((a,b)=>b.size-a.size).slice(0,5),byCategory};});
function parseList(value:unknown):string[]{try{const v=JSON.parse(String(value||'[]'));return Array.isArray(v)?v.map((x:unknown)=>String(x)):[]}catch{return []}}
function loadRules():OrganizationRule[]{return (all('SELECT * FROM rules ORDER BY priority,id') as any[]).map(r=>({id:r.id,name:r.name,fileTypes:parseList(r.file_types),extensions:parseList(r.extensions?.trim().startsWith('[')?r.extensions:JSON.stringify(r.value?[String(r.value).replace(/^\./,'')]:[])),keywords:parseList(r.keywords),destination:r.destination||r.target||'',enabled:Boolean(r.enabled),priority:Number(r.priority)||0}));}
ipcMain.handle('rules:list',()=>loadRules());
ipcMain.handle('rules:save',(_e,input:any)=>{const existing=input.id?all('SELECT priority FROM rules WHERE id=?',[Number(input.id)])[0] as any:undefined;const rule:OrganizationRule={id:Number(input.id)||undefined,name:String(input.name||'').trim(),fileTypes:[...new Set<string>((Array.isArray(input.fileTypes)?input.fileTypes:String(input.fileTypes||'').split(/[;,]+/)).map((x:string)=>x.trim()).filter(Boolean))],extensions:[...new Set<string>((Array.isArray(input.extensions)?input.extensions:String(input.extensions||'').split(/[;,\s]+/)).map((x:string)=>x.trim().toLowerCase().replace(/^\*?\./,'')).filter(Boolean))],keywords:[...new Set<string>((Array.isArray(input.keywords)?input.keywords:String(input.keywords||'').split(/[;,\n]+/)).map((x:string)=>x.trim().toLowerCase()).filter(Boolean))],destination:validateRuleDestination(String(input.destination||'')),enabled:input.enabled!==false,priority:input.priority===undefined?Number(existing?.priority)||0:Number(input.priority)||0};if(!rule.name)throw Error('Enter a rule name.');if(!rule.extensions.length&&!rule.keywords.length&&!rule.fileTypes.length)throw Error('Add a file type, extension, or filename keyword.');if(rule.extensions.some(e=>!/^([a-z0-9][a-z0-9_-]*)$/.test(e)))throw Error('Extensions can contain letters, numbers, underscores, or hyphens.');if(rule.fileTypes.some(t=>![...Object.values(categories),'Other'].includes(t)))throw Error('Choose a supported file category.');if(rule.id){db.run('UPDATE rules SET name=?,file_types=?,extensions=?,keywords=?,destination=?,enabled=?,priority=? WHERE id=?',[rule.name,JSON.stringify(rule.fileTypes),JSON.stringify(rule.extensions),JSON.stringify(rule.keywords),rule.destination,Number(rule.enabled),rule.priority,rule.id]);persist();return rule.id;}const next=(all('SELECT COALESCE(MAX(priority),-1)+1 AS p FROM rules')[0] as any).p;return run('INSERT INTO rules(name,condition,operator,value,action,target,file_types,extensions,keywords,destination,enabled,priority) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[rule.name,'custom','matches','', 'Move to',rule.destination,JSON.stringify(rule.fileTypes),JSON.stringify(rule.extensions),JSON.stringify(rule.keywords),rule.destination,Number(rule.enabled),next]);});
ipcMain.handle('rules:delete',(_e,id:number)=>{run('DELETE FROM rules WHERE id=?',[id]);return true;});
ipcMain.handle('rules:enabled',(_e,id:number,enabled:boolean)=>{run('UPDATE rules SET enabled=? WHERE id=?',[Number(enabled),id]);return true;});
ipcMain.handle('rules:reorder',(_e,ids:number[])=>{db.run('BEGIN');ids.forEach((id,i)=>db.run('UPDATE rules SET priority=? WHERE id=?',[i,id]));db.run('COMMIT');persist();return loadRules();});
ipcMain.handle('settings:get',()=>Object.fromEntries(all('SELECT * FROM settings').map((x:any)=>[x.key,JSON.parse(x.value)])));ipcMain.handle('settings:save',(_e,s:any)=>{db.run('BEGIN');for(const [k,v]of Object.entries(s))db.run('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)',[k,JSON.stringify(v)]);db.run('COMMIT');persist();return true;});
ipcMain.handle('files:demo',()=>[{name:'video.mp4',category:'Videos',destination:'Videos/video.mp4',size:48200000},{name:'logo.png',category:'Images',destination:'Images/logo.png',size:2400000},{name:'resume.pdf',category:'Documents',destination:'Documents/resume.pdf',size:640000},{name:'song.mp3',category:'Audio',destination:'Audio/song.mp3',size:5100000},{name:'project.zip',category:'Archives',destination:'Archives/project.zip',size:83000000},{name:'design.psd',category:'Design Files',destination:'Design Files/design.psd',size:97000000}].map(x=>({...x,path:`Downloads/${x.name}`,modified:new Date().toISOString()})));
